# Generated by Django 4.0.5 on 2022-06-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_num', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField(max_length=300)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
